# Generated by Django 3.1.4 on 2020-12-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201206_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='Описание', max_length=5000),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='Описание для СЕО', max_length=240),
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(default='Ключевые слова для СЕО', max_length=240),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(default='Ссылка партнерки', max_length=5000),
        ),
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.CharField(default='Ссылка на Лого', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='Название Оффера', max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
