# Generated by Django 3.1.4 on 2020-12-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_percent_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='percent_per_day',
            field=models.FloatField(default=0.0),
        ),
    ]
