# Generated by Django 3.1.4 on 2020-12-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20201212_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate_partner',
            name='account',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliate_partner',
            name='api_key',
            field=models.CharField(default='api_key', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='partner',
            field=models.ManyToManyField(default='0', to='posts.Affiliate_Partner'),
        ),
    ]
