# Generated by Django 3.1.4 on 2020-12-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20201212_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Methot_Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('logo', models.ImageField(upload_to='static/images/withdraw/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='partner',
            field=models.ManyToManyField(to='posts.Affiliate_Partner'),
        ),
        migrations.AddField(
            model_name='post',
            name='withdraw',
            field=models.ManyToManyField(to='posts.Methot_Withdraw'),
        ),
    ]
