# Generated by Django 3.1.4 on 2020-12-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20201212_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate_partner',
            name='account',
        ),
        migrations.AddField(
            model_name='post',
            name='offer_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='methot_withdraw',
            name='name',
            field=models.CharField(max_length=160, unique=True),
        ),
    ]
