# Generated by Django 3.1.4 on 2020-12-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20201222_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='Описание', max_length=5000, verbose_name='Подробная Информация'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='Описание для СЕО', max_length=240, verbose_name='Описание для СЕО'),
        ),
        migrations.AlterField(
            model_name='post',
            name='first_credit_free',
            field=models.BooleanField(default=False, verbose_name='Первый Займ Бесплатно'),
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(default=' ', max_length=240, verbose_name='Ключевые слова для СЕО'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(default='Ссылка', max_length=5000, verbose_name='Ссылка партнерки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(upload_to='static/images/mfo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='post',
            name='max_credit',
            field=models.IntegerField(default=0, verbose_name='Максимальный Займ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='max_days',
            field=models.IntegerField(default=0, verbose_name='Максимальное количество дней'),
        ),
        migrations.AlterField(
            model_name='post',
            name='min_credit',
            field=models.IntegerField(default=0, verbose_name='Минимальный Займ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='min_days',
            field=models.IntegerField(default=0, verbose_name='Минимальное количество дней'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='Название Оффера', max_length=240, unique=True, verbose_name='Название МФО'),
        ),
        migrations.AlterField(
            model_name='post',
            name='offer_id',
            field=models.IntegerField(default=0, verbose_name='ID Оффера'),
        ),
        migrations.AlterField(
            model_name='post',
            name='offer_status',
            field=models.BooleanField(default=True, verbose_name='Оффер включен'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pament',
            field=models.IntegerField(default=0, verbose_name='Вознаграждение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='partner',
            field=models.ManyToManyField(to='posts.Affiliate_Partner', verbose_name='Партнерка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='percent_per_day',
            field=models.FloatField(default=0.0, verbose_name='Минимальный процент в день'),
        ),
        migrations.AlterField(
            model_name='post',
            name='scope',
            field=models.IntegerField(default=100, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='Название МФО'),
        ),
        migrations.AlterField(
            model_name='post',
            name='withdraw',
            field=models.ManyToManyField(to='posts.Methot_Withdraw', verbose_name='Способы Вывода Займа'),
        ),
    ]
