# Generated by Django 3.1.4 on 2021-01-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20201228_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='offer_want',
            field=models.BooleanField(default=True, verbose_name='Оффер в Проверке'),
        ),
    ]
